In [3]:
import random

import os
from tqdm import tqdm

import numpy as np
import matplotlib.pyplot as plt

import soundfile as sf
import librosa
import librosa.display
import random
from hmmlearn import hmm

import IPython.display as idp

# 푸리에 변환을 위한 라이브러리
import math
from scipy.interpolate import splrep, splev

## GMM-HMM

In [4]:
np.random.seed(0)
n_samples =100
n_features = 1
observed_data = np.random.randn(n_samples, n_features)

In [5]:
n_states =3 # 은닉상태수 
n_components =2 # GMM components
n_iterations = 10 # EM 반복 횟수 

In [6]:
# GMM-HMM생성
model = hmm.GMMHMM(n_components= n_states, n_mix =n_components,covariance_type = 'diag', n_iter=n_iterations,
                    random_state= 0)# 모델 생성
model.fit(observed_data)
                    

GMMHMM(covars_prior=array([[[-1.5],
        [-1.5]],

       [[-1.5],
        [-1.5]],

       [[-1.5],
        [-1.5]]]),
       covars_weight=array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]]),
       means_prior=array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]]),
       means_weight=array([[0., 0.],
       [0., 0.],
       [0., 0.]]),
       n_components=3, n_mix=2, random_state=0,
       weights_prior=array([[1., 1.],
       [1., 1.],
       [1., 1.]]))

In [7]:
# 디코딩(추론)
new_observed_data = np.random.randn(n_samples, n_features)
log_likelihood, state_sequence =model.decode(new_observed_data)

In [8]:
print(f'GMM-HMM Transition Matrix: \n{model.transmat_}')
print(f'\nGMM-HMM Means : \n{model.means_}')
print(f'\nGMM-HMM Covariance :\n{model.covars_}')
print(f'\nGMM-HMM Mixing Weights : \n {model.weights_}')

print(f'\n\nDecoded state sequence :\n {state_sequence}')

GMM-HMM Transition Matrix: 
[[1.79047330e-01 4.72591277e-01 3.48361393e-01]
 [1.59355497e-03 5.05360107e-05 9.98355909e-01]
 [9.73700185e-01 2.59338904e-02 3.65925036e-04]]

GMM-HMM Means : 
[[[-0.32495488]
  [ 0.21348363]]

 [[ 0.75333689]
  [ 0.19405407]]

 [[ 0.09248296]
  [-0.21138654]]]

GMM-HMM Covariance :
[[[0.9277494 ]
  [0.8089055 ]]

 [[0.94887448]
  [1.11405218]]

 [[0.94456122]
  [0.90421287]]]

GMM-HMM Mixing Weights : 
 [[0.50437089 0.49562911]
 [0.35022433 0.64977567]
 [0.69479007 0.30520993]]


Decoded state sequence :
 [1 2 0 2 0 1 2 0 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 2 0 1 2 0 1 2 0 2 0 1 2
 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0
 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [ ]:
print(f'GMM-HMM Transition Matrix: \n{model.transmat_}')
print(f'\nGMM-HMM Means : \n{model.means_}')
print(f'\nGMM-HMM Covariance :\n{model.covars_}')
print(f'\nGMM-HMM Mixing Weights : \n {model.weights_}')

print(f'\n\nDecoded state sequence :\n {state_sequence}')

GMM-HMM Transition Matrix: 
[[1.79047330e-01 4.72591277e-01 3.48361393e-01]
 [1.59355497e-03 5.05360107e-05 9.98355909e-01]
 [9.73700185e-01 2.59338904e-02 3.65925036e-04]]

GMM-HMM Means : 
[[[-0.32495488]
  [ 0.21348363]]

 [[ 0.75333689]
  [ 0.19405407]]

 [[ 0.09248296]
  [-0.21138654]]]

GMM-HMM Covariance :
[[[0.9277494 ]
  [0.8089055 ]]

 [[0.94887448]
  [1.11405218]]

 [[0.94456122]
  [0.90421287]]]

GMM-HMM Mixing Weights : 
 [[0.50437089 0.49562911]
 [0.35022433 0.64977567]
 [0.69479007 0.30520993]]


Decoded state sequence :
 [1 2 0 2 0 1 2 0 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 2 0 1 2 0 1 2 0 2 0 1 2
 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0
 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [ ]:
print(f'GMM-HMM Transition Matrix: \n{model.transmat_}')
print(f'\nGMM-HMM Means : \n{model.means_}')
print(f'\nGMM-HMM Covariance :\n{model.covars_}')
print(f'\nGMM-HMM Mixing Weights : \n {model.weights_}')

print(f'\n\nDecoded state sequence :\n {state_sequence}')

GMM-HMM Transition Matrix: 
[[1.79047330e-01 4.72591277e-01 3.48361393e-01]
 [1.59355497e-03 5.05360107e-05 9.98355909e-01]
 [9.73700185e-01 2.59338904e-02 3.65925036e-04]]

GMM-HMM Means : 
[[[-0.32495488]
  [ 0.21348363]]

 [[ 0.75333689]
  [ 0.19405407]]

 [[ 0.09248296]
  [-0.21138654]]]

GMM-HMM Covariance :
[[[0.9277494 ]
  [0.8089055 ]]

 [[0.94887448]
  [1.11405218]]

 [[0.94456122]
  [0.90421287]]]

GMM-HMM Mixing Weights : 
 [[0.50437089 0.49562911]
 [0.35022433 0.64977567]
 [0.69479007 0.30520993]]


Decoded state sequence :
 [1 2 0 2 0 1 2 0 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 2 0 1 2 0 1 2 0 2 0 1 2
 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0
 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
